name: AWS Architect Deploy

on:
  push:
    branches:
    - master

jobs:
  build:
    name: Architect-Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1.4.4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build
    - name: Deploy Stage
      run: yarn deploy:arc
      env:
        aws_region: us-west-1
    - name: commit-staging-yaml
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish staging'
        name: thisguymartin
        email: martin@gizmodlabs.com
